/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package studentregistrationsystem;
import java.awt.Toolkit;
import java.awt.event.WindowEvent;
import javax.swing.JOptionPane;

/**
 *
 * @author Ravindu_Dassanayake
 */
public class LoginPage extends javax.swing.JFrame {

    /**
     * Creates new form LoginPage
     */
    public LoginPage() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        cmdbut_login = new javax.swing.JButton();
        txt_username = new javax.swing.JTextField();
        combox_division = new javax.swing.JComboBox<>();
        cmdbut_clear = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        pfield_pword = new javax.swing.JPasswordField();
        lbl_background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Username:");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(201, 187, -1, -1));

        jLabel2.setText("Password:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(201, 227, -1, -1));

        jLabel3.setText("Division:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 270, -1, -1));

        cmdbut_login.setText("Login");
        cmdbut_login.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdbut_loginActionPerformed(evt);
            }
        });
        getContentPane().add(cmdbut_login, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 410, -1, -1));

        txt_username.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_usernameActionPerformed(evt);
            }
        });
        getContentPane().add(txt_username, new org.netbeans.lib.awtextra.AbsoluteConstraints(328, 184, 126, -1));

        combox_division.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "ADMINISTRATOR" }));
        getContentPane().add(combox_division, new org.netbeans.lib.awtextra.AbsoluteConstraints(328, 271, 130, -1));

        cmdbut_clear.setText("Cancel");
        cmdbut_clear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdbut_clearActionPerformed(evt);
            }
        });
        getContentPane().add(cmdbut_clear, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 410, -1, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jLabel4.setText("System Login ");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 30, 150, 60));
        getContentPane().add(pfield_pword, new org.netbeans.lib.awtextra.AbsoluteConstraints(328, 224, 126, -1));

        lbl_background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/studentregistrationsystem/Images/JFrame bg/Login-Background.jpeg"))); // NOI18N
        getContentPane().add(lbl_background, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 680, 560));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cmdbut_loginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdbut_loginActionPerformed
        // TODO add your handling code here:
        String password = pfield_pword.getText();
        String username = txt_username.getText();
        
        if (password.contains("admin123") && username.contains("admin") ){
              txt_username.setText("");
              pfield_pword.setText("");
              MainMenu mm = new MainMenu();
              mm.setVisible(true);
              this.dispose();
        }     
        else{
              JOptionPane.showMessageDialog(null,"The username or the Password entered is Incorrect\n Click OK to enter the password again","Login Control",JOptionPane.ERROR_MESSAGE);
              pfield_pword.setText("");
              txt_username.setText("");
                         
        }
                    
       
    }//GEN-LAST:event_cmdbut_loginActionPerformed

    private void txt_usernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_usernameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_usernameActionPerformed

    private void cmdbut_clearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdbut_clearActionPerformed
        // TODO add your handling code here:
        txt_username.setText("");
        pfield_pword.setText("");
        
    }//GEN-LAST:event_cmdbut_clearActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LoginPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LoginPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LoginPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LoginPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LoginPage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cmdbut_clear;
    private javax.swing.JButton cmdbut_login;
    private javax.swing.JComboBox<String> combox_division;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel lbl_background;
    private javax.swing.JPasswordField pfield_pword;
    private javax.swing.JTextField txt_username;
    // End of variables declaration//GEN-END:variables
}
